
[build]
  command = "npm run build"
  publish = "dist"
  base = "DigitalniAsistenti/opt/build/repo/main"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 